### ISSUE TITLE
[Bug]: lsd -la takes a long time

### ISSUE THREAD

**Issue by mrpmohiburrahman** [lsd-rs/lsd#1003]
### Version

- [X] latest

### version

lsd 1.0.0

### What OS are you seeing the problem on?

macOS

### installation

brew reinstall lsd

### term

xterm-256color

### ls-colors

di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43

### What happened?

```markdown
When I tried to run "lsd -la", it took a lot of time to show the output
```

### What expected?

```markdown
It should show the output as soon as possible just like other options.
```

**Comment by zwpaper** [comment]
We have some performance issues for large dirs, please check https://github.com/lsd-rs/lsd/issues/378

I will start to work on it after the v1.1.0 releases in days
