### ISSUE TITLE
How to dynamically configure color scheme?

### ISSUE THREAD

**Issue by bartekpacia** [lsd-rs/lsd#1009]
On my MacBook, I use light theme in my terminal during the day and dark theme during the night. By default, `lsd` looks great on black background, but on white it's barely legible:
<img width="571" alt="Screenshot 2024-03-13 at 17 36 39" src="https://github.com/lsd-rs/lsd/assets/40357511/235a2b2d-55e1-45a2-944c-598b61e4a73f">

Similar problems arise in many CLI tools (e.g. [`micro`](github.com/zyedidia/micro) editor), but I [solved it like this](https://github.com/zyedidia/micro/issues/2509#issuecomment-1992921327):

```zsh
if command -v micro >/dev/null 2>&1; then
    if [ "$(uname)" = Darwin ]; then
        # automatically set light/dark theme on macOS
        alias micro="micro -colorscheme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo monokai || echo bubblegum)"
    fi
fi
```

I'd like to do the same with `lsd`, but unfortunately it looks like it only accepts following values:

```
$ lsd --color <TAB COMPLETION>
always  auto    never
```

How can I dynamically select the theme like I showed in the first snippet above?

**Comment by j-lakeman** [comment]
I would also be interested in this. Same thing on Linux.
Great application regardless!

**Comment by j-lakeman** [comment]
See #208

**Comment by zwpaper** [comment]
hi the lsd theme can only be configured by configuration file or read from the theme file, please have a look at the configuration part in README

**Comment by haohanyuzmx** [comment]
i know it can config by color.yaml, but is it can use dynamic color
