### ISSUE TITLE
Documentation is inaccurate

### ISSUE THREAD

**Issue by m147** [lsd-rs/lsd#1011]
The documentation on the main page is inaccurate
for example:
git status does not work; gives errors 
`  # When "custom" is set, lsd will look in the config directory for colors.yaml.`
does not work; give error: 
`lsd: Not a valid theme: /home/m147/.config/lsd/themes/custom, No such file or directory (os error 2).`
probably others

Might want to fix it

**Comment by zwpaper** [comment]
Hi, the change is introduced in a newer version, please try the newly released v1.1.1
