### ISSUE TITLE
[Bug]: lsd-v1.1.0-aarch64-unknown-linux-musl reports 1.0.0 as version

### ISSUE THREAD

**Issue by pro-sumer** [lsd-rs/lsd#1012]
### Version

- [X] latest

### version

lsd 1.0.0

### What OS are you seeing the problem on?

Linux

### installation

Manually extracting https://github.com/lsd-rs/lsd/releases/download/v1.1.0/lsd-v1.1.0-aarch64-unknown-linux-musl.tar.gz

### term

xterm-256color

### ls-colors

no=00;38;5;244:di=37:ln=34:so=1;30:pi=1;30:ex=32:bd=1;30:cd=1;30:su=32:sg=32:tw=33:ow=33

### What happened?

```markdown
`lsd --version` outputs `lsd 1.0.0`
```

### What expected?

```markdown
`lsd --version` outputs `lsd 1.1.0`
```

### What else?

```markdown
n/a
```

**Comment by pro-sumer** [comment]
Same for lsd-v1.1.0-aarch64-unknown-linux-gnu.tar.gz (and maybe more?).

**Comment by tranzystorekk** [comment]
The bug is in that new release was cut without bumping version in `Cargo.toml`/`Cargo.lock`

**Comment by zwpaper** [comment]
thanks for the quick catch!
fixed in https://github.com/lsd-rs/lsd/releases/tag/v1.1.1
