### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by alec-c4** [lsd-rs/lsd#1032]
- os: macOS Sonoma
- `lsd --version`: lsd 1.1.2
- `echo $TERM`: xterm-256color 
- `echo $LS_COLORS`: di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43

## Expected behavior
<img width="540" alt="SCR-20240415-jpme" src="https://github.com/lsd-rs/lsd/assets/25312/661ff1c4-5ead-493e-87ad-467b36a3e8b1">

## Actual behavior
<img width="843" alt="SCR-20240415-jnky-4" src="https://github.com/lsd-rs/lsd/assets/25312/42213722-1211-47a5-a2cf-5eb846eeb747">

something is wrong with nvim icon, but i have Nerd Fonts installed

**Comment by zwpaper** [comment]
The font you use doesn't have the nvim icon, pls try another font, there is nothing lsd can help with

**Comment by zwpaper** [comment]
we use `f36f` for nvim logo, you can check it https://www.nerdfonts.com/cheat-sheet.
you can also try in terminal: `printf '\\uf36f'`

your font may not contain this icon, please try another one.
