### ISSUE TITLE
compdef: unknown command or service: lsd

### ISSUE THREAD

**Issue by touero** [lsd-rs/lsd#1061]
- os: 
- `lsd --version`: 1.1.2
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43

When I use `exec zsh` it will appear:

![截屏2024-06-16 17 17 54](https://github.com/lsd-rs/lsd/assets/61647484/a49e14a9-e7f0-44a8-a553-d38bc2ac1c77)

**Comment by zwpaper** [comment]
it should be something wrong with your `.zshrc` where mentioned the lsd completion

**Comment by touero** [comment]
add a line: `compdef _lsd lsd`
