### ISSUE TITLE
[Bug]: v1.1.5 on GitHub Releases has an odd binary(?) file without any os, arch, or package designation

### ISSUE THREAD

**Issue by coolaj86** [lsd-rs/lsd#1090]
### Version

- [X] latest

### version

N/A

### What OS are you seeing the problem on?

Others

### installation

N/A

### term

N/A

### ls-colors

N/A

### What happened?

If you take a look at https://github.com/lsd-rs/lsd/releases/tag/v1.1.5 you can see that there's a file just called `lsd` - without any OS, Arch, Platform, or Package designation to it.

I'm guessing this is an errant test file from a folder section process?

(or is this intentional and something we can expect going forward? if so, what is it?)

### What expected?

All release files to have consistent designations in line with previous releases, using common triple-host and source naming conventions. "the usual"

### What else?

I discovered this due to some package linting that went awry on https://webinstall.dev/lsd, which caused `lsd` downloads to fail for users since this morning.

Obviously my release linting should be logging warnings rather than throwing errors for such things. Ooops. Fixed that.

**Comment by zwpaper** [comment]
good catch, it's due to the ci, i have to update it manually, let me fix it now
