### ISSUE TITLE
Weird green background

### ISSUE THREAD

**Issue by Kush-Dhingra** [lsd-rs/lsd#1106]
- os: Windows with WSL ubuntu lts 22.04
- `lsd --version`: lsd 1.1.5
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`:   (blank)

![image](https://github.com/user-attachments/assets/70a7b9a7-1d83-452a-8c53-d3c74ebfe2cc)
As you can see the weird green background for the projects dir, I dont have any configs

**Comment by zwpaper** [comment]
try `ls -lh`, it's should because of the 777 permission. it's not necessary most of the time.

you could refer to somewhere like https://unix.stackexchange.com/questions/241726/fix-ls-colors-for-directories-with-777-permission
