### ISSUE TITLE
Create a git integration

### ISSUE THREAD

**Issue by Peltoche** [lsd-rs/lsd#7]

**Comment by alichtman** [comment]
Can you explain what kind of git integration you're looking to add?

**Comment by Peltoche** [comment]
Hello @alichtman,

There is no defined specs yet. This feature is already implemented by the colorls and the exa projects, I think it can be a good start to check how they do it.

**Comment by ysf** [comment]
There is an example on the exa website: https://the.exa.website/features/git

Basically there is a new column that displays the git status for the files in the listed directory. (new, modified etc..)

**Comment by Peltoche** [comment]
Seems cool. I think that we can do something even better with the icons support. I don't know if we should add a new icons for the git status or just override the existing one. We can also add a new column of course.

**Comment by cjbassi** [comment]
Another tool to check out that displays the git status of files is [ranger](https://github.com/ranger/ranger). I like their use of icons, and I also like that they display the git status of entire repos too, so you could `ls` the current directory and see which repos are dirty. [Screenshot](https://ranger.github.io/screenshots/vcs.png).

**Comment by leomikezee** [comment]
Maybe add a option or a flag to hide files based on the .gitignore file

**Comment by patevs** [comment]
I definitely support this. Would be useful to be able to see the current git status of files and also being able to hide files based on the .gitignore file.

**Comment by aseifert** [comment]
+1 from me! I'd really love to have this as well, it's the only thing I still miss from exa/colorls!

**Comment by sherifabdlnaby** [comment]
+1!!!!

**Comment by hpwxf** [comment]
I like this idea; maybe I can do it. Is there already someone on this issue ?

About the icons, if we want funny glyphs, my suggestions are (from https://www.nerdfonts.com/cheat-sheet)
        * check (-): nf-fa-check f00c
        * modified (M): nf-fa-gear f013
        * uknown (?): nf-fa-user_secret f21b 
        * ignored (!) : nf-mdi-ghost f79f (or nf-fa-exclamation f12a)
        * new (+) : nf-mdi-login_variant fafb 
<img width="688" alt="Capture d’écran 2021-02-28 à 13 11 49" src="https://user-images.githubusercontent.com/26146722/109418054-a4c82e00-79c6-11eb-848c-8f0ace7fea05.png">

The display should be with two columns (staged, not staged)

To get git info, I can use libgit2 (https://github.com/rust-lang/git2-rs)

Is there any other constraint ?

**Comment by zwpaper** [comment]
Hi @hpwxf , There is noone working on this right now, please feel free to take this up and thanks for contributing to LSD!

as the icons part, maybe we should have @meain 's attention, 
for my personal opinion, it is cute! XD

PS: 
I was thinking to work on a configuration file for the icons after the theme one, so do not let the glyphs stop your progress

**Comment by meain** [comment]
Hey @hpwxf, thanks a lot for taking looking into this. I have not been able to fully think through it but here are few things that I wanted to mention.

I don't think separating the output of ls to two columns would be a good idea, this should be just a "block" similar to size or date. As for the representation, we could use how [git-status](https://git-scm.com/docs/git-status) represents it with two items (working tree and index). This would make the data familiar to read. We kinda loose the details on partially staged files for example if we stick to just one char/icon.

About the icons, I think icons should be optional as this feature should also be usable by people who do not have the proper fonts setup.  We could have this configurable and make it use icons, but I am not also worried if having two icons close together would look good.

Related to the implementation, when listing a top level folder `lsd` should be able to notify even if there is some change in some file that is under a specific folder.

**Comment by hpwxf** [comment]
To define a status for a directory, I suggest to use a kind of *max* on the status of the files inside.
I use this order:
```
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum GitStatus {
    /// No changes
    Unmodified,
    /// Entry is ignored item in workdir
    Ignored,
    /// Entry does not exist in old version
    New,
    /// Type of entry changed between old and new
    Typechange,
    /// Entry does not exist in new version
    Deleted,
    /// Entry was renamed between old and new
    Renamed,
    /// Entry content changed between old and new
    Modified,
    /// Entry in the index is conflicted
    Conflicted,
}
```
it means that a conflict will always be shown whatever the other modifications; if no conflict, the second most important status is Modified...

Below, a output example (fancy icons will come later). For this example, in the previous commit, each sub/directory contained two files file1 and file2.
![Snapshot](https://user-images.githubusercontent.com/26146722/109704469-ef98a000-7b96-11eb-8945-53da11212896.png)

Is it what you expect ?

**Comment by meain** [comment]
@hpwxf That sounds good.

**Comment by typkrft** [comment]
Completely unsolicited, but Git Integration with in a manner similar to colorls in the grid view would be really nice for at a glance information.

**Comment by hpwxf** [comment]
> Completely unsolicited, but Git Integration in a manner similar to colorls in the grid view would be really nice for at a glance information.

After this PR is merged, this seems to be a doable improvement.

**Comment by sherifabdlnaby** [comment]
I love `lsd`, I prefer it over `exa` but I miss the Git Integration, why has this feature not been considered yet?

**Comment by hpwxf** [comment]
For sure, PR #495 should be updated.

Is there only this remark https://github.com/Peltoche/lsd/pull/495#issuecomment-965972260 to solve?

**Comment by LucaAngioloni** [comment]
Any news on this?

**Comment by hpwxf** [comment]
Thank you to ask. It seems useful to update my PR. I will try to do on next Wednesday (Feb 15th).
I hope the code hasn't changed too much since my first version.

**Comment by meain** [comment]
@hpwxf Thanks for the interest. I unfortunately don't have much time these days to look into major features in lsd. I'm fine if @zwpaper can take up review of this one. Just wanted to give you a heads up so as to not waste your time.

**Comment by zwpaper** [comment]
Hi @meain @hpwxf, I also do not have much time for this significant feature, but luckily we have already done most of the work previously, let's keep going and I will try my best to make it happen.

**Comment by hpwxf** [comment]
I'm rebasing my previous work on master branch. `--git` option seems to work again.

I have many `#[cfg(feature = "git")]` to support git as an optional feature.

What do you prefer? default feature or optional feature ?

**Comment by meain** [comment]
I'm thinking it could be enabled on systems that support it. Don't think there is any point in keeping it optional.

**Comment by hpwxf** [comment]
Ok; the only unsupported arches are:
* arm-unknown-linux-gnueabihf
* i686-pc-windows-gnu

Before the PR, I've just something to check about 
* display of git icons even if `--icons=never`
* Simplify the deactivation of the `git` feature (when not supported; cf list above)
* proper icons for *fancy* theme; any suggestion is welcome 
  (cf https://github.com/Peltoche/lsd/issues/7#issuecomment-787442823)
* issues related in https://github.com/Peltoche/lsd/pull/495#issuecomment-965972260

and it should be done (hopefully in a few days).

**Comment by hpwxf** [comment]
It's almost done. To fix issues shown in my previous PR, I need to know how to manage the case where we have:
1. a sub-directory 'subdir' that uses git (but not the current one): show or not a git status for `subdir`?
2. a sub-directory that uses git and the current one also uses git + option `--tree`:  show git status related to current dir or a status as if we use `git status` inside each subdirectory?

In other words, do you consider that the output of `exa -l --git [--tree]` is what we want?

Here my demo to plau this
[demo.zip](https://github.com/Peltoche/lsd/files/10834660/demo.zip)

And some comparisons on it between `exa` and my proposal.

Case 1.:
<img width="443" alt="exa-1" src="https://user-images.githubusercontent.com/26146722/221435595-48158206-b7c5-49c1-8ecd-63a0819ba690.png">
<img width="702" alt="lsd-1" src="https://user-images.githubusercontent.com/26146722/221435601-2a925a01-8d85-4864-9cc5-7778a8b16363.png">

Case 2.:
<img width="454" alt="exa-2" src="https://user-images.githubusercontent.com/26146722/221435611-098717b2-739f-499c-945a-2a98708779d9.png">

<img width="657" alt="lsd-2" src="https://user-images.githubusercontent.com/26146722/221435618-b527dc9e-e8c4-4cb4-b1bd-b5547a0dc092.png">

**Comment by zwpaper** [comment]
hi @hpwxf, in my opinion, I would vote +1 for the `exa` output, as `git status` also output like this.

**Comment by hpwxf** [comment]
I'm waiting two days for any other suggestions, and then I push my PR.
