### ISSUE TITLE
Support for winget

### ISSUE THREAD

**Issue by Zamiell** [lsd-rs/lsd#735]
In the installation instructions, it says for Windows users to use `scoop`.
But `winget` is the official Windows package manager, and everyone already has this installed on their Windows 10 already without having to do anything, so I propose that this software is installable with `winget`.

**Comment by meain** [comment]
None of the existing pakcages are maintained by the lsd maintainers, but I'll keep this issue open to discuss on anything that can be done from the lsd side to help with packages or any other discussion around it.

**Comment by ehawman** [comment]
I would recommend using Winget for GUI applications, and scoop.sh for CLI tools like lsd. I find that things run a lot smoother that way.

Just a recommendation, not a solution to the lack of lsd on Winget.

**Comment by sitiom** [comment]
- PR: https://github.com/microsoft/winget-pkgs/pull/94721
