### ISSUE TITLE
lsd --directory-only --tree --depth 2

### ISSUE THREAD

**Issue by sizur** [lsd-rs/lsd#747]
- os: `Darwin`, `Linux`
- `lsd --version`: `lsd 0.22.0`
- `echo $TERM`: `xterm-256color`
- `echo $LS_COLORS`: _irrelevant_

## Expected behavior
`tree -dL 2` shows directory structure with depth of 2.

## Actual behavior
`lsd --directory-only --tree --depth 2` fails with error:
```
error: The argument '--depth <num>...' cannot be used with '--directory-only'

USAGE:
    lsd --color <color>... --date <date>... --depth <num>... --directory-only --hyperlink <hyperlink>... --icon <icon>... --icon-theme <icon-theme>... --ignore-glob <pattern>... --permission <permission>... --size <size>... --tree

For more information try --help
```

**Comment by meain** [comment]
I don't remember what but I trying to do that and it causing some issue when used without tree. Just give it a shot and if you don't find any problems, feel free to open a PR for this change.

**Comment by nim65s** [comment]
Hi,

I couldn't find any issue, in the sense that `lsd --directory-only` and `lsd --directory-only **.rs` behave in the same way before and after the change.
