### ISSUE TITLE
Windows support for `.config/lsd`

### ISSUE THREAD

**Issue by Fleshgrinder** [lsd-rs/lsd#758]
On Windows `lsd` only looks at `%APPDATA%/lsd` and ignores `%USERPROFILE%/.config/lsd`. This platform difference makes it unnecessarily harder to write portable dotfiles across several platforms. It would be great to reconsider this stance and ensure that all platforms behave the same way.

**Comment by meain** [comment]
We could probably look into `%USERPROFILE%/.config/lsd` if no config was found at `%APPDATA%/lsd`.

**Comment by Destroy666x** [comment]
+1 for XDG support on WIndows also - not sure why it's not. Bunch of cross-system CLI apps have it implemented well - prioritize XDG everywhere, then go for system specific locations such as `%APPDATA%`. E.g. most git related CLI apps and some of similar utility ones.

Any opinion @meain?

**Comment by ofersadan85** [comment]
@zwpaper I'd be happy to write up a PR for this if you still need help

**Comment by zwpaper** [comment]
thanks so much, @ofersadan85, it would be great that you could help, I will look into the PR ASAP and then we could release the v1.1.0
