### ISSUE TITLE
Looking to contribute, need feedback

### ISSUE THREAD

**Issue by TruncatedDinosour** [lsd-rs/lsd#764]
Hello, LSD devs,

I got some ideas of what to add and I want to hear your
opinion on what is a good idea to add, because, once again, I am looking
to contribute to this project :)

## Fixes

- Improve `*.asm` icon
- Fix the icon of executable files

## Files and dirs

- .rustup/ --  Rustup (rust update (?)) files
- .editorconfig -- Standard config for editors
- \*.list -- Lists of data
- user-dirs.dirs -- XDG user dirs config
- \*.env -- Environment files
    - .env -- Global environment
- doc/ -- documentation
- src/ -- source code
- tests/ -- Tests for code
    - test/ -- Test dir
- \_\_pycache\_\_/ -- Python bytecode cache
    - requirements.txt -- Python requirements file
    - runtime.txt -- Required python version
    - tox.ini -- Python tox config
- scripts/ -- Scripts dir
- UNLICENSE -- Standard name for the Unlicense 'license'
    - MAINTAINERS -- List of maintainers
    - COPYRIGHT -- Copyright statement
- home/ -- User home dirs
    - lib64/ -- 64-bit libs
    - bin/ -- Binaries
    - var/ -- Variable files
    - share/ -- Sharable text
    - usr/ -- Universal system repository
    - dev/ -- Device files
    - boot/ -- Bootloader files
    - opt/ -- Optional applications
    - mnt/ -- Mounts
    - proc/ -- Processes
    - sbin/ -- System binaries
    - sys/ -- System files
- .\*_history -- History files for readline-like
    - .bash_history -- BASH shell history
    - .bpython_history -- BPython python REPL history
    - .gdb_history -- GDB debugger history
    - .lesshst -- `less` history
    - .sqlite_history -- SQLite3 history
- Media/ -- Media dir
- .idlerc/ -- Python IDLE dir
    - .lynxrc -- Lynx browser configuration
    - inputrc -- Readline config
        - .inputrc -- User readline config
    - .kshrc -- KSH shell config
    - wgetrc -- Wget config
        - .wgetrc -- User wget config
    - .shellcheckrc -- Shellcheck config
    - zathurarc -- Zathura config
- .gnupg/ -- Gpg files and config
    - .pki/ -- SSL dir
    - .dbus/ -- DBUS dir
    - Xauthorty -- Xorg authentication file
        - .Xmodmap -- Xorg key bindings file
        - .xprofile -- Xorg profile
- .mailcap -- Metamail config
- .mozilla/ -- Mozilla software dir
- .mutt/ -- Mutt email client directory
- .jupyter/ -- Jupyter files
- rc.conf -- OpenRC config
    - init.d/ -- OpenRC services
- mime.types -- Mime types
- \*.old -- Old files
    - \*.bak -- Backup files
- Kbuild -- Kernel build file
    - Kconfig -- Kernel config file
    - Module.symvers -- Kernel module debug symbols
    - Kconfig.\* -- Specific kernel config file
    - Kbuild.\* -- Specific kernel build file
- Makefile\* -- Make config
    - \*.mk -- Make include/module
- \*.orig -- Original files
- vim/ -- Files for the`vim` editor
    - nvim/ -- Files for the`neovim` editor
    - vimrc -- Vim config
    - \*.snippets -- Vim snippets
- \*.lss -- Lynx browser style sheet
- licenses/ -- Licenses
- \*.url -- URL files
- os-release -- Distro info
    - lsb-release -- Distro info
- api/ -- API
- content/ -- Content dir
    - js -- JavaScript dir
        - ts -- TypeScript dir
    - img -- Images
    - styles -- Styles
        - css -- CSS
        - scss -- SCSS
        - sass -- SASS
- favicons/ -- Favicons
- page/ -- Pages
- resources/ -- Resources for programs
    - static/ -- Static resources
    - public/ -- Public resources
- netlify.toml -- Configuration for Netlify
- backups/ -- Backups
- completions/ -- Shell completions
- venv/ -- Virtualenv for python
- .eslintrc.* -- ESlint config for JavaScript
- target/ -- Target files
- dist/ -- Destination files
    - dest/ -- Destination files
- \*.ebuild -- Gentoo ebuild/package files
    - \*.eclass -- Gentoo ebuild classes
    - Manifest -- Gentoo package manifest
    - metadata.xml -- Gentoo package metadata
    - metadata/ -- Gentoo repository metadata
- TODO\* -- TODOs
    - FAQ\* -- FAQ
    - LEGACY\* -- Legacy statement
- \*.info -- Info files
- \*.hh -- C++ header files
- .local/ -- Local files
    - local/ -- Local files
- \*.j2 -- Jinja2 templating language files
    - \*.jinja -- Jinja templating language files
- config.\* -- Configuration files
    - \*.dat -- Data files
- \*.rl -- Readline scripts
- conf.d -- Configuration dir
    - \*.conf.d -- Specific configuration dir
- \*.{1..8} -- Sectioned manual page file
    - \*.man -- Manual page file

Hope to hear some feedback ! Will start working on implementing them
once I hear it :D

**Comment by meain** [comment]
We would love to get icon updates. You can update/add new icons at https://github.com/Peltoche/lsd/blob/master/src/theme/icon.rs . Feel free to take a look at the issues to see any other ones that you would like to contribute to as well.

**Comment by zwpaper** [comment]
I am closing this, https://github.com/lsd-rs/lsd/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-desc would always be a good start, or we can open a https://github.com/orgs/lsd-rs/discussions if there is something could be discussed

/close
