### ISSUE TITLE
lsd always shows an error

### ISSUE THREAD

**Issue by GhostShadow0316** [lsd-rs/lsd#823]
- os: Windows 10 Pro 22H2
- `lsd --version`: lsd 0.22.0
- `echo $TERM`: 
- `echo $LS_COLORS`: 

## Expected behavior
show the result without the errors

## Actual behavior
When I run `lsd` in `D:\` or `C:\`, it show those error before the result:
```
lsd: .\DumpStack.log.tmp: The process cannot access the file because it is being used by another process. (os error 32).
lsd: .\pagefile.sys: The process cannot access the file because it is being used by another process. (os error 32).

lsd: .\System Volume Information: Access is denied. (os error 5).

lsd: .\WindowsApps: The access control list (ACL) structure is invalid. (os error 1336).
```
but if I'm in any folder, it won't show those error

**Comment by hasecilu** [comment]
Probably those are protected files. Probably while trying to get the  size?
When I use `lsd -l` I get `lsd: ./protected_file/pgdb: Permission denied (os error 13).` error but is because those files have not read permission for my user, totally expected not a bug.
Maybe a `--quiet` flag?

**Comment by zwpaper** [comment]
I am not familiar with Windows, is there something like `2>/dev/null` to mute errors?

**Comment by zwpaper** [comment]
/close

as it was a permission error and could be muted by redirecting the stderr
