### ISSUE TITLE
I'm not sure this time is a problem, as shown

### ISSUE THREAD

**Issue by sdcxzx-tester** [lsd-rs/lsd#827]
- os: 
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.

## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.
<img width="645" alt="image" src="https://user-images.githubusercontent.com/122763218/228132301-0b8ee0e2-5e81-4c76-96b2-e8131d87b58d.png">

**Comment by meain** [comment]
If you are meant the icons not showing up correctly, you'll have to setup Nerd  Fonts for that to work.
[Here](https://www.youtube.com/watch?v=mQdB_kHyZn8) is great video explaining this in detail.
