### ISSUE TITLE
[Bug] Double width icons and the codepoint change in Nerd Fonts Material Design Icons

### ISSUE THREAD

**Issue by tkapias** [lsd-rs/lsd#836]
- os: Debian testing
- `lsd --version`: 0.23.1
- `echo $TERM`: tmux-256color (inside rxvt-unicode-256color)
- `echo $LS_COLORS`: ""

## Issue

**Some icon glyphs chosen for lsd are not displayed as single wide in mono and it breaks the visual alignment with other lines.**
  - I made a list of these icons and tested in urxvt, rxvt and st terminals and with different NerdFonts Mono fonts, even after patching my own.
  - Sometimes the icon is aligned to left or center but always on 2 spaces.

![image](https://user-images.githubusercontent.com/45816387/232502713-906c4b20-423d-44bf-b9ae-13fc490ae4a8.png)

![image](https://user-images.githubusercontent.com/45816387/232502926-fe63004b-0f59-47c7-8de6-dd79cbf160f9.png)

Those glyphs are in a collection of glyphs with a scaling problem in mono.

I printed all the glyphs in my patched font and here are the ones with a width problem:

![image](https://user-images.githubusercontent.com/45816387/232508009-6c1d4faf-51b9-43de-bea5-2fccf8c149b9.png)

## Context

With its [latest](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) release NerdFonts project announced that Material Design glyphs where moved to a new codepoint and the old one will be deleted in the futur.

Exemple, the glyph used for torrents is marked as obsolete:

![image](https://user-images.githubusercontent.com/45816387/232503907-ad7d0651-4427-450f-ac24-e8c688ae2dc0.png)

Sadly, [they wrote that they fixed some scaling issue too](https://github.com/ryanoasis/nerd-fonts/pull/773) but the new glyph is too wide even when I use the last fontpatcher.
Maybe that it will change with a next release.

## Questions

The fact that these icons codepoints will soon be obsolete is a good occasion to rethink the icons choices.

Can you check if you can reproduce this issue, and find alternatives for these icons at least?

- double width characters in `icon.rs` (display nicelay in the bowser but not in most terminals)

``` rust
impl ByType {
    pub fn unicode() -> Self {
        ByType {
            dir: "\u{1f4c2}".into(),           // '📂'
            file: "\u{1f4c4}".into(),          // '📄'
            pipe: "\u{1f4e9}".into(),          // '📩'
            socket: "\u{1f4ec}".into(),        // '📬'
            symlink_file: "\u{1f516}".into(),  // '🔖'
            device_block: "\u{1f4bd}".into(),  // '💽'
            special: "\u{1f4df}".into(),       // '📟'
        }
    }
}

            ("api", "\u{f98c}"),             // "歷"
            ("bio", "\u{f910}"),             // "蘿"
            ("fpl", "\u{f910}"),             // "蘿"
            ("m3u8", "\u{f910}"),            // "蘿"
            ("m3u", "\u{f910}"),             // "蘿"
            ("pls", "\u{f910}"),             // "蘿"
            ("rproj", "\u{fac5}"),           // "鉶"
            ("torrent", "\u{f98c}"),         // "歷"
            ("vlc", "\u{f910}"),             // "蘿"
            ("wpl", "\u{f910}"),             // "蘿"
```

**Comment by tkapias** [comment]
Correction about my list extracted from `icon.rs`:

- **The first block contains emojis and not glyphs, so it's no related to this issue**. It's normal that emojis are scaled differently. I don't know where lsd use them.

``` rust
impl ByType {
    pub fn unicode() -> Self {
        ByType {
            dir: "\u{1f4c2}".into(),           // '📂'
            file: "\u{1f4c4}".into(),          // '📄'
            pipe: "\u{1f4e9}".into(),          // '📩'
            socket: "\u{1f4ec}".into(),        // '📬'
            symlink_file: "\u{1f516}".into(),  // '🔖'
            device_block: "\u{1f4bd}".into(),  // '💽'
            special: "\u{1f4df}".into(),       // '📟'
        }
    }
}
```

**Comment by zwpaper** [comment]
hi @tkapias, thanks for the report and investigation, is it means that if we change the built-in icon to new codepoints, the issue should be gone?

**Comment by tkapias** [comment]
Yes, it solved the issue on my setup, with a font generated from the last Nerd Fonts release.

You will have to inform the users of 'material-nf' of this change in the release because they will have to update their fonts to Nerd-Fonts =< 2.3.3.

**Comment by brainsik** [comment]
Unclear whether I should use this issue or open a new one. With Nerd Fonts 3.0.0, fancy folder icons now look like this:

<img width="76" alt="image" src="https://user-images.githubusercontent.com/162998/236040111-4d5cc782-6dd6-45d2-b35a-2d1a21dd03c1.png">

Specifically, this is with FiraCode Nerd Font, but I believe all Nerd Font patched fonts will be like this.

This is the translation table to the new code point locations:
https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287

**Comment by zwpaper** [comment]
fixed in https://github.com/lsd-rs/lsd/pull/830

/close
