### ISSUE TITLE
Problem with nonicons (kittye terminal)

### ISSUE THREAD

**Issue by RAprogramm** [lsd-rs/lsd#858]
- os: 
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: xterm-kitty
- `echo $LS_COLORS`: 
![2023-06-18-100151_hyprshot](https://github.com/lsd-rs/lsd/assets/70325462/0783739e-740f-4bec-844a-9df81148602a)

with nonicons incorrect directory icons.
i have this string in my kitty config:
`symbol_map U+f101-U+f25c nonicons`

this change icons in neovim, but not in lsd

**Comment by zwpaper** [comment]
it should be something related to the font configuration, there is nothing we can do on lsd, please check your font or nonicons setting.

/close
