### ISSUE TITLE
Suggestion: custom/default config setting for colors & icons seems redundant

### ISSUE THREAD

**Issue by peppidesu** [lsd-rs/lsd#865]
This is in response to a review conversation I had with @zwpaper in #851.

Currently, in order to modify icons/colors, one must create an `icons.yaml` (or `colors.yaml`) and additionally specify in the config file to use the custom icons/colors. This because of consitency reasons prior to the changes made in #851

With the new color scheme system in place this step becomes somewhat redundant and deviates from what is considered conventional. 

I suggest that - similarly to how we deprecated the old color scheme system - we make lsd autodetect these files and fall back to the default otherwise. The user can then specify a flag somehow to force lsd to use the default schemes. Of course we should still support old behavior with a corresponding warning message.

**Comment by zwpaper** [comment]
On a second consideration, I found it seems to be reasonable to set the `custom` option as we have two more `default` and `no-color` options.

let's close this one and start the v1.0 release

/close
