### ISSUE TITLE
lsd: Not a valid theme, No such file or directory (os error 2).

### ISSUE THREAD

**Issue by FLYISFOOL** [lsd-rs/lsd#870]
I configure the color theme according to readme.md:
> Color theme can be configured in the [configuration file](https://github.com/lsd-rs/lsd#configuration)(color.theme), The valid theme > configurations are:
> - default: the default color scheme shipped in lsd
> - custom: use a custom color scheme defined in colors.yaml
> - (deprecated) theme_file_name(yaml): use the theme file to specify colors(without the yaml extension)
> 
> When set to custom, lsd will look for colors.yaml in the XDG Base Directory, e.g. ~/.config/lsd/colors.yaml
> When configured with the theme-file-name which is a yaml file, lsd will look up the theme file in the following way:
> - relative name: check the XDG Base Directory, e.g. ~/.config/lsd/themes/.yaml
> 
> - absolute name: use the file path and name to find theme file

When I set color.theme to custom, and put colors.yaml in the XDG Base Directory, lsd reported an error:
```
lsd: Not a valid theme: /home/stupid_user/.config/lsd/themes/custom, No such file or directory (os error 2).
```

From the error message,  custom has no effect. LSD looks for color theme in theme_file_name way. Has anyone encountered this problem?

**Comment by zwpaper** [comment]
how do you install lsd? master is not yet released, it could only be used by install from source code

**Comment by FLYISFOOL** [comment]
So that's it, thanks. I installed lsd using pacman. The readme is a bit confusing. Lsd has not been updated yet, but the document has already been updated.😂
