### ISSUE TITLE
[Bug]: no M2 mac Support

### ISSUE THREAD

**Issue by trueblooda** [lsd-rs/lsd#875]
### Version

- [X] latest

### version

<img width="860" alt="image" src="https://github.com/lsd-rs/lsd/assets/85261024/d5b41d4f-07f4-4e14-849c-25eeb23fd289">

lsd --version unavailable spits out the same error message. 

### What OS are you seeing the problem on?

macOS

### installation

the guide

### term

xterm-256color

### ls-colors

Gxfxcxdxbxegedabagacad

### What happened?

```markdown
no output
```

### What expected?

```markdown
output
```

### What else?

```markdown
no
```

**Comment by zwpaper** [comment]
how do you install lsd? what do you mean by `the guide`?

homebrew has arm support, and we will release the Apple Silicon version in the coming release.

**Comment by zwpaper** [comment]
/close 

in favor of https://github.com/lsd-rs/lsd/issues/844
