### ISSUE TITLE
[Feature request] Don't list files in gitignore

### ISSUE THREAD

**Issue by frankebel** [lsd-rs/lsd#886]
An option like `--git-ignore` in [exa](https://github.com/ogham/exa) or `--gitignore` in tree which does not list files that are ignored by git. For example if I have `foo.bar` in my gitignore that file will not be listed.

**Comment by zwpaper** [comment]
thanks @frankebel, we had a related discuss here https://github.com/lsd-rs/lsd/issues/218, please refer to it and discuss it there.

/close
