### ISSUE TITLE
Unable to disable quotes (no support for: `--quoting-style`, `QUOTING_STYLE`, or `--literal`)

### ISSUE THREAD

**Issue by globau** [lsd-rs/lsd#894]
### Version

- [X] latest

### version

lsd 1.0.0

### What OS are you seeing the problem on?

macOS

### installation

homebrew

### term

xterm-256color

### ls-colors

di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43

### What happened?

```markdown
`error: unexpected argument '--literal' found`
```

### What expected?

```markdown
`lsd` should honour `lsd --literal`, `lsd --quoting-style=literal`, and/or `QUOTING_STYLE=literal lsd`
```

### What else?

```markdown
Sadly #746 added quotes around filenames without any way to opt out.

See https://www.gnu.org/software/coreutils/quotes.html for the various options that GNU's `ls` provides.

Adding just `literal` initially would be valuable to those who are not in favour of this somewhat controversial change.
```

**Comment by zwpaper** [comment]
thanks for the advice! 
/kind feature
/good-first-issue
/help
