### ISSUE TITLE
[Bug]: fish completions directory wrong

### ISSUE THREAD

**Issue by Korkman** [lsd-rs/lsd#899]
### Version

- [X] latest

### version

1.0.0
Tested release files:
lsd-musl_1.0.0_amd64.deb
lsd_1.0.0_amd64.deb

### What OS are you seeing the problem on?

Linux

### installation

dpkg -i

### What happened?

```markdown
Fish completions end up in
/usr/share/fish/completions/completions
```

### What expected?

```markdown
Should be
/usr/share/fish/vendor_completions.d
```

**Comment by zwpaper** [comment]
it looks like fish ship its own completions in `/usr/share/fish/completions/completions`, and vendors should put it in `/usr/share/fish/vendor_completions.d`

ref: https://fishshell.com/docs/current/completions.html

/milestone v1.1.0
/kind enhancement
/area packaging
