### ISSUE TITLE
lsd used to install on 64bit Raspberry Pi, but v1.0.0 can't

### ISSUE THREAD

**Issue by upyesp** [lsd-rs/lsd#908]
- os: 64 bit Pi OS (previous know as Raspbian), bullseye, latest release.
- `lsd --version`: 1.0.0
- `echo $TERM`:  xterm-256color
- `echo $LS_COLORS`: 

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.

download the latest .deb with:
```
wget https://github.com/Peltoche/lsd/releases/latest/download/lsd_1.0.0_arm64.deb
```
attempt to install with:
```
sudo dpkg -i lsd_1.0.0_arm64.deb
```

Returns the following error... "uses unknown compression...".  Unfortunately, the `zst` compression method is not supported by 64bit Pi OS.

Earlier versions of lsd install fine on 64bit Pi OS.  So an effective work-around is to install the latest version of lsd that wasn't packaged using zst compression, which is: lsd_0.23.1_arm64.deb

Request, please build a .deb of v1.0.0 for arm which uses the compression method used for previous versions of lsd.  This will enable installations on the current version of Pi OS (64bit).

Thanks :)

**Comment by zwpaper** [comment]
It's mainly because of the compression changes in dpkg, please check https://github.com/lsd-rs/lsd/issues/891
