### ISSUE TITLE
sample config.yaml contains invalid fields

### ISSUE THREAD

**Issue by dimitrilw** [lsd-rs/lsd#922]
- os: MacOS Sonoma 14.0, current as of time of this post
- `lsd --version`: 1.0.0, installed 10 mins ago via Homebrew
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: `none -- empty return value` (see pic, below)

## Expected behavior
Process all fields given in [sample config.yaml content](https://github.com/lsd-rs/lsd#config-file-content).

## Actual behavior
```
lsd: Configuration file /Users/dimitri/.config/lsd/config.yaml format error, unknown field `literal`, expected one of `classic`, `blocks`, `color`, `date`, `dereference`, `display`, `icons`, `ignore-globs`, `indicators`, `layout`, `recursion`, `size`, `permission`, `sorting`, `no-symlink`, `total-size`, `symlink-arrow`, `hyperlink`, `header` at line 143 column 1.
```
...and:
```
lsd: Configuration file /Users/dimitri/.config/lsd/config.yaml format error, unknown field `truncate-owner`, expected one of...
```

<img width="295" alt="image" src="https://github.com/lsd-rs/lsd/assets/5898931/a16d5890-9c74-4620-80b8-b9d9a7340a6d">

**Comment by zwpaper** [comment]
Hi @dimitrilw , the master is for the latest dev features, you can check 1.0 by changing the code to v1.0.0 tag

Can you also help adding a notice under configuration in readme?

**Comment by dimitrilw** [comment]
Thank you for that explanation. ...it is always a 50/50 chance on "is main (aka master) prod, or is main dev" 😄 ...anyway, since your repo's primary readme is the main branch, that's what users (like me) will probably expect to match the released version -- worth adding header statement pointing peeps to old readme files hidden in release branches

**Comment by rlovell3** [comment]
The config file issues just tripped me up as well on a fresh (10-minutes ago) install.

**Comment by zwpaper** [comment]
sorry for that @rlovell3, fixed now by https://github.com/lsd-rs/lsd/pull/960
