### ISSUE TITLE
[Bug]: Example config.yaml is not valid

### ISSUE THREAD

**Issue by dcechano** [lsd-rs/lsd#931]
### Version

- [X] latest

### version

`lsd 0.23.1`

### What OS are you seeing the problem on?

Linux

### installation

`sudo dnf install lsd`

### What happened?

```markdown
copy and pasted the example config file from the `READ_ME.md` into a config.yaml and ran `lsd --config-file ~/.config/lsd/config.yaml` and got:

`lsd: Configuration file /home/dylan/.config/lsd/config.yaml format error, unknown field `literal`, expected one of `classic`, `blocks`, `color`, `date`, `dereference`, `display`, `icons`, `ignore-globs`, `indicators`, `layout`, `recursion`, `size`, `permission`, `sorting`, `no-symlink`, `total-size`, `symlink-arrow`, `hyperlink`, `header` at line 139 column 1.

thread 'main' panicked at 'Provided file path is invalid', src/main.rs:126:33
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

Clearly the parse fails when it stumbles on `literal: false` but I am not sure why. Is `literal` no longer supported? If so I can submit a PR with it removed.
```

### What expected?

```markdown
I expected the file to parse.
```

**Comment by mikeharty** [comment]
I caught this too, it looks like the main branch is just ahead of the latest release (release still pinned at 1.0.0, [quite a bit new since then](https://github.com/lsd-rs/lsd/compare/v1.0.0...HEAD).) Probably best to build from source.

**Comment by zwpaper** [comment]
the master branch is meant to be the dev branch, please select the tag of your version to view the versioned docs

We have another issue tracking this to add a notice

/close
