### ISSUE TITLE
[Bug]: no icon for ‘LICENCE’

### ISSUE THREAD

**Issue by Equationzhao** [lsd-rs/lsd#939]
### Version

- [X] latest

### version

lsd 1.0.0

### What OS are you seeing the problem on?

macOS

### installation

brew install lsd

### term

xterm-256color

### ls-colors

no output

### What happened?

```markdown
The 'LICENSE' file has an icon but the 'LICENCE' does not.
```

### What expected?

```markdown
the 'LICENCE' has the same icon as the 'LICENSE'
```

**Comment by Equationzhao** [comment]
<img width="193" alt="image" src="https://github.com/lsd-rs/lsd/assets/75521101/1cb96d2b-7306-4146-bec6-86128c8c99de">

**Comment by zwpaper** [comment]
Hi @Equationzhao, thanks for reporting this, It could be done by using the icon theme currently as we now support that.

or it would be great if you could submit a PR to fix it.

**Comment by zwpaper** [comment]
fixed now
