### ISSUE TITLE
[Feature request]: More frequent updates?

### ISSUE THREAD

**Issue by StrictlyMonad** [lsd-rs/lsd#948]
I have been using lsd for quite some time and just noticed that the latest update does not include the features I was looking for in the released version. And after viewing the version release history I noticed that the package was previously updated 1 year ago.

Is there any reason for this infrequent update schedule? If so, is there any room for a quicker release schedule? Even a pre-release tag would be useful IMO!

Otherwise, I would like to thank everyone who helped bring this package to its current state! :)

**Comment by zwpaper** [comment]
v1.0.0 is released at Aug 28, please check https://github.com/lsd-rs/lsd/releases/tag/v1.0.0
