### ISSUE TITLE
Feature request: pipe into lsd

### ISSUE THREAD

**Issue by elkarouh** [lsd-rs/lsd#950]
Hi,

I would like to use fd in conjunction with lsd.
fd is very good at filtering files. It produces a list of paths.
However lsd is very good at rendering the paths.
I would like to have something like:
`fd -d2 -e rs regex_pattern | lsd`

Regards

**Comment by riquito** [comment]
Most of the time for this kind of behaviour you use `xargs`

` fd -d2 -e rs regex_pattern | xargs lsd`

Does that work for you?

**Comment by elkarouh** [comment]
Yes, it works!
