### ISSUE TITLE
Would this functionality be accepted as contribution?

### ISSUE THREAD

**Issue by mortkaptilo** [lsd-rs/lsd#951]
What i have in mind is, when displaying directories and files, an index or a number could be displayed with them  in side, and they become temporary aliases for the corresponding file/directory.  

Something like that 
```
$ lsd --withindex
1.  Desktop/
2.  Documents/
3.  Downloads/
4.  Music/
5.  Pictures/
6.  Videos/
7.  .bashrc
8.  .gitconfig
9.  report.pdf

$ cd 2

```
If you think this functionality is a bad idea or out of scope, please let me know so that i wouldn't be wasting my time.

**Comment by zwpaper** [comment]
hi @mortkaptilo, thanks for the idea, but I have to say that it's really out of the lsd scope, maybe you could consider some other solutions from a shell or terminal emulator, [warp.dev](https://www.warp.dev/?utm_source=github&utm_medium=referral&utm_campaign=lsd_20231001) maybe a good choice
