### ISSUE TITLE
Cannot install lsd version 1.0.0

### ISSUE THREAD

**Issue by cabiamdos** [lsd-rs/lsd#963]
- os: parrot os
- `lsd --version`: 5.3
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: <no output>

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.
When I try to install latest version I received this error. I have asked chatgpt and the solution didn't work. But version 0.2 is working fine

## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.

```
> sudo dpkg -i lsd-musl_1.0.0_amd64.deb
dpkg-deb: error: archive 'lsd-musl_1.0.0_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive lsd-musl_1.0.0_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 lsd-musl_1.0.0_amd64.deb
```

**Comment by zwpaper** [comment]
please check https://github.com/lsd-rs/lsd/issues/891

/close
