### ISSUE TITLE
[Bug] Tree is much slower with lsd than exa. 

### ISSUE THREAD

**Issue by m-nelly** [lsd-rs/lsd#971]
- os: Linux
- `lsd --version`: 1.0.0
- `echo $TERM`: xterm-kitty

## Expected behavior
Directory trees should generate at somewhat comparable speeds between tools. 

## Actual behavior
Command `lsd --tree` run in ~/ takes roughly two seconds to generate any output and then generates the whole tree whereas `exa --tree` generates the full output in less than one second.

**Comment by zwpaper** [comment]
we have an issue tracking this, and I will try to do some improvement in the next release

https://github.com/lsd-rs/lsd/issues/378

**Comment by luketych** [comment]
Yes it is very very slow to the point of being unusable. Please fix, it's not that difficult. I can share my code for a custom tree command that prints in real-time and executes in less than 1 second.
