### ISSUE TITLE
Icons not showing up in ZSH

### ISSUE THREAD

**Issue by alifiroozi80** [lsd-rs/lsd#977]
Hello Folks
I have installed the `lsd` with homebrew.
My problem is that the icons are not showing up:

![Screen Shot 2024-01-13 at 12 20 57 PM](https://github.com/lsd-rs/lsd/assets/81459625/a6ce3b0d-2fe6-48d3-bb57-0d0a9ef7b69e)

- os: MacOS
- lsd version: `lsd 1.0.0`:
- Term: `xterm-256colo` 
- shell: `ZSH`

**Comment by zwpaper** [comment]
lease check https://github.com/lsd-rs/lsd#prerequisites

/close
