### ISSUE TITLE
Help on how to generate completions!! Documentation insufficient

### ISSUE THREAD

**Issue by DanielRivasMD** [lsd-rs/lsd#994]
- os: 
- `lsd --version`: 
- `echo $TERM`: 
- `echo $LS_COLORS`: 

## Expected behavior
If applicable, add the output of the classic ls command (`\ls -la`) in order to show the buggy file/directory.

## Actual behavior
If the application panics run the command with the trace (`RUST_BACKTRACE=1 lsd ...`).
In case of graphical errors, add a screenshot if possible.

**Comment by zwpaper** [comment]
just download the release tar https://github.com/lsd-rs/lsd/releases/tag/v1.0.0 and there are fish and bash completion files
